### ISSUE TITLE
UndefVarError and LoadError when running test/exampleobs.jl

### ISSUE THREAD

**Issue by dkilda** [XingyuZhang2018/AD-Kitaev#1]
I'm trying to run the tests, but I get a number of LoadErrors and UndefVarErrors from pretty much every test module. Since there are too many errors to list all of them, here is one example. 

test/exampleobs.jl gives LoadError: UndefVarError: obs_bcenv not defined. It seems like it fails to import obs_bcenv from BCVUMPS package (which I've installed in the default Julia environment). I've checked BCVUMPS, and indeed I couldn't locate obs_bcenv anywhere in the code. 

> exampleobs tests running...
> exampleobs: Error During Test at /home/kilda/Desktop/AD-Kitaev/test/runtests.jl:25
>   Got exception outside of a @test
>   LoadError: UndefVarError: obs_bcenv not defined
>   Stacktrace:
>     [1] include(fname::String)
>       @ Base.MainInclude ./client.jl:451
>     [2] macro expansion
>       @ ~/Desktop/AD-Kitaev/test/runtests.jl:27 [inlined]
>     [3] macro expansion
>       @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
>     [4] macro expansion
>       @ ~/Desktop/AD-Kitaev/test/runtests.jl:26 [inlined]
>     [5] macro expansion
>       @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
>     [6] top-level scope
>       @ ~/Desktop/AD-Kitaev/test/runtests.jl:5
>     [7] include(fname::String)
>       @ Base.MainInclude ./client.jl:451
>     [8] top-level scope
>       @ REPL[5]:1
>     [9] top-level scope
>       @ ~/.julia/packages/CUDA/tTK8Y/src/initialization.jl:52
>    [10] eval
>       @ ./boot.jl:373 [inlined]
>    [11] eval_user_input(ast::Any, backend::REPL.REPLBackend)
>       @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
>    [12] repl_backend_loop(backend::REPL.REPLBackend)
>       @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:244
>    [13] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
>       @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:229
>    [14] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
>       @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:362
>    [15] run_repl(repl::REPL.AbstractREPL, consumer::Any)
>       @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:349
>    [16] (::Base.var"#930#932"{Bool, Bool, Bool})(REPL::Module)
>       @ Base ./client.jl:394
>    [17] #invokelatest#2
>       @ ./essentials.jl:716 [inlined]
>    [18] invokelatest
>       @ ./essentials.jl:714 [inlined]
>    [19] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
>       @ Base ./client.jl:379
>    [20] exec_options(opts::Base.JLOptions)
>       @ Base ./client.jl:309
>    [21] _start()
>       @ Base ./client.jl:495
>   in expression starting at /home/kilda/Desktop/AD-Kitaev/test/exampleobs.jl:4
>

**Comment by XingyuZhang2018** [comment]
I apologize for the inconvenience. BCVUMPS.jl is becoming obsolete because TeneT.jl has a better implementation that includes it. Therefore, testing including BCVUMPS in AD-Kitaev has been disabled as well.

If you want to learn how AD-Kitaev works and run tests, I suggest running tests in TeneT.jl as I'm confident they will work well.

Finally, I will fix the test in AD-Kitaev soon.
