### ISSUE TITLE
UndefVarError when running test/variationalipeps.jl

### ISSUE THREAD

**Issue by dkilda** [XingyuZhang2018/AD-Kitaev#2]
In relation to the other issue #1, here is another example.

test/variationalipeps.jl gives UndefVarError: SquareBCIPEPS not defined. The test module uses SquareBCIPEPS, but cannot find it (I haven't been able to locate it manually either, whether in BCVUMPS or in AD-Kitaev, or anywhere else).

> variationalipeps tests running...
> non-interacting with Array{Float64}: Error During Test at /home/kilda/Desktop/AD-Kitaev/test/variationalipeps.jl:33
>   Test threw exception
>   Expression: energy(h, SquareBCIPEPS(a), oc, key) / 2 ≈ -1
>   UndefVarError: SquareBCIPEPS not defined
>   Stacktrace:
>    [1] macro expansion
>      @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
>    [2] macro expansion
>      @ ~/Desktop/AD-Kitaev/test/variationalipeps.jl:33 [inlined]
>    [3] top-level scope
>      @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1359

Both here and in the other issue #1 , it seems like the tests require some external code, either from BCVUMPS or elsewhere, but are not able to find it. (I intend to make some developments on top of your package, so it would be very useful to have working tests, to make sure that I don't break any of the existing functionality).

**Comment by XingyuZhang2018** [comment]
Tests are available in TeneT.jl and I will rewrite the tests in AD-Kitaev.

**Comment by XingyuZhang2018** [comment]
Additionally, there is a simple [demo](https://github.com/XingyuZhang2018/TeneT_demo/blob/master/demo/demo.ipynb) of TeneT showcasing 2D iPEPS optimization in a square lattice.

**Comment by dkilda** [comment]
Great, thank you very much for fixing it! All the tests are running and passing fine now. I'll go check out TeneT as well.
